### PR TITLE
chore: merge last changes from dAppBooster(core)

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
# Description:

- Merge last changes from dAppBooster(core)
- Fix conflicts.
- Fix broken demos.

### CODE REVIEW

**Comment by fernandomg** [comment]
fixed the build (wrong env variable due to the other temp PR, sorry)

---

@nicosampler I may have broken something, but it took quite a long time (actually, changing the window focus for the transaction request to actually appear in the wallet... well, I think it's my setup and has nothing to do with the implementation, but anyways).

image

Then, when all finish, I get the button asking for me to Send 10K which I no longer have, and get an error toast (is this last one intentional to display the error?)

image

---
@gabitoesmiapodo it's still in draft for some reason?

**Comment by gabitoesmiapodo** [comment]
@fernandomg was this broken for some reason?

**Comment by gabitoesmiapodo** [comment]
@fernandomg 

> I may have broken something, but it took quite a long time (actually, changing the window focus for the transaction request to actually appear in the wallet... well, I think it's my setup and has nothing to do with the implementation, but anyways).

It's you.

@fernandomg @nicosampler 

> Then, when all finish, I get the button asking for me to Send 10K which I no longer have, and get an error toast (is this last one intentional to display the error?)

This was an existing error, the demo doesn't detect that the transaction has finished and the UI is not updated to reflect that. You have to reload the page so it changes.

Fix here? Later?

**Comment by fernandomg** [comment]
> Fix here? Later?

Later

**Comment by fernandomg** [comment]
> @fernandomg was this broken for some reason?

The last failure was due to the SGs URLs, that I changed its structure for the other PR 😬

**Review by fernandomg — APPROVED** [review]

**Comment by nicosampler** [comment]
> @fernandomg
> 
> > I may have broken something, but it took quite a long time (actually, changing the window focus for the transaction request to actually appear in the wallet... well, I think it's my setup and has nothing to do with the implementation, but anyways).
> 
> It's you.
> 
> @fernandomg @nicosampler
> 
> > Then, when all finish, I get the button asking for me to Send 10K which I no longer have, and get an error toast (is this last one intentional to display the error?)
> 
> This was an existing error, the demo doesn't detect that the transaction has finished and the UI is not updated to reflect that. You have to reload the page so it changes.
> 
> Fix here? Later?

I've seen this problem before, and it was because the RPC wasn't working properly. Please try with a custom RPC to see if it is still happening. For me, it is working fine. 

I'll take a look at this: "Then, when all finish, I get the button asking for me to Send 10K"

**Pull request merged**
